# Kleborate module.

pick_kleborate_table <- function(txt_files) {
  if (length(txt_files) == 0) {
    return(NULL)
  }
  parsed <- purrr::map(
    txt_files,
    ~ tryCatch(readr::read_tsv(.x, show_col_types = FALSE), error = function(e) NULL)
  )
  scored <- purrr::map_int(parsed, function(df) {
    if (is.null(df) || nrow(df) == 0) {
      return(-1L)
    }
    nm <- names(df)
    # Prefer tables that contain Kleborate typing/virulence-related columns.
    sum(c("species", "Species", "st", "ST", "lineage", "virulence_score", "virulence_score/kleb") %in% nm)
  })
  idx <- which.max(scored)
  if (length(idx) == 0 || scored[idx] < 0) {
    return(NULL)
  }
  parsed[[idx]]
}

run_kleborate <- function(manifest_df, cfg, out_dir, tools) {
  raw_dir <- file.path(out_dir, "kleborate_raw")
  fs::dir_create(raw_dir)
  out_rows <- purrr::map_dfr(seq_len(nrow(manifest_df)), function(i) {
    sid <- manifest_df$Sample_ID[i]
    fasta <- manifest_df$Input_FASTA[i]
    sample_dir <- file.path(raw_dir, sid)
    fs::dir_create(sample_dir)
    status <- "not_run"
    species <- NA_character_
    lineage <- NA_character_
    virulence_score <- NA_real_
    aerobactin <- NA_character_
    salmochelin <- NA_character_
    rmpA <- NA_character_
    rmpA2 <- NA_character_
    warn_reason <- NA_character_

    log_info(glue::glue("[Kleborate] ({i}/{nrow(manifest_df)}) {sid}"))

    if (!is.null(tools[["kleborate"]]) && nzchar(tools[["kleborate"]])) {
      res <- tryCatch(
        run_external_tool(
          tools[["kleborate"]],
          args = c("-a", fasta, "-o", sample_dir, "-p", "kpsc")
        ),
        error = function(e) NULL
      )
      if (!is.null(res) && isTRUE(res$status == 0)) {
        status <- "ok"
        readr::write_lines(res$stdout, file.path(sample_dir, "kleborate.stdout.log"))
        readr::write_lines(res$stderr, file.path(sample_dir, "kleborate.stderr.log"))
        txt <- list.files(sample_dir, pattern = "\\.txt$", full.names = TRUE)
        df <- pick_kleborate_table(txt)
        if (!is.null(df) && nrow(df) > 0) {
          nm <- names(df)
          get_col <- function(x) if (x %in% nm) as.character(df[[x]][1]) else NA_character_
          species <- dplyr::coalesce(get_col("species"), get_col("Species"))
          lineage <- dplyr::coalesce(get_col("st"), get_col("ST"), get_col("lineage"))
          virulence_score <- suppressWarnings(as.numeric(dplyr::coalesce(get_col("virulence_score"), get_col("virulence_score/kleb"), NA_character_)))
          aerobactin <- dplyr::coalesce(get_col("iuc"), get_col("aerobactin"))
          salmochelin <- dplyr::coalesce(get_col("iro"), get_col("salmochelin"))
          rmpA <- get_col("rmpA")
          rmpA2 <- get_col("rmpA2")
          if (all(is.na(c(species, lineage, virulence_score, aerobactin, salmochelin, rmpA, rmpA2)))) {
            warn_reason <- "No typing/virulence columns found in Kleborate output tables."
          }
        } else {
          warn_reason <- "No readable .txt output generated by Kleborate."
        }
      } else {
        status <- "failed"
        warn_reason <- "Kleborate command failed."
        if (!is.null(res)) {
          readr::write_lines(res$stdout, file.path(sample_dir, "kleborate.stdout.log"))
          readr::write_lines(res$stderr, file.path(sample_dir, "kleborate.stderr.log"))
        }
      }
    } else {
      warn_reason <- "kleborate executable not available."
    }

    if (!is.na(warn_reason)) {
      log_warn(glue::glue("[Kleborate] {sid}: {warn_reason}"))
    }
    tibble::tibble(
      Sample_ID = sid,
      Kleborate_Status = status,
      Species = species,
      ST_or_Lineage = lineage,
      Kleborate_Virulence_Score = virulence_score,
      Aerobactin = aerobactin,
      Salmochelin = salmochelin,
      rmpA = rmpA,
      rmpA2 = rmpA2
    )
  })
  readr::write_tsv(out_rows, file.path(out_dir, "kleborate_summary.tsv"))
  out_rows
}
