# Kleborate module.

# Prefer tables that look like Kleborate typing/virulence outputs (v2 short names or v3 module prefixes).
kleborate_column_score <- function(nm) {
  score <- sum(c(
    "species", "Species", "st", "ST", "lineage",
    "virulence_score", "virulence_score/kleb",
    "enterobacterales__species__species",
    "klebsiella_pneumo_complex__mlst__ST",
    "klebsiella_pneumo_complex__virulence_score__virulence_score"
  ) %in% nm)
  # Soft credit for any v3-style module columns.
  score + as.integer(any(grepl("__mlst__ST$|__species__species$|__virulence_score__", nm)))
}

pick_kleborate_table <- function(txt_files) {
  if (length(txt_files) == 0) {
    return(NULL)
  }
  # Prefer the main complex table over hAMRonization companion outputs.
  ranked <- txt_files[order(
    grepl("hAMRonization", basename(txt_files), ignore.case = TRUE),
    grepl("klebsiella_pneumo_complex_output\\.txt$", basename(txt_files)) * -1L
  )]
  parsed <- purrr::map(
    ranked,
    ~ tryCatch(readr::read_tsv(.x, show_col_types = FALSE), error = function(e) NULL)
  )
  scored <- purrr::map_int(parsed, function(df) {
    if (is.null(df) || nrow(df) == 0) {
      return(-1L)
    }
    kleborate_column_score(names(df))
  })
  idx <- which.max(scored)
  if (length(idx) == 0 || scored[idx] < 0) {
    return(NULL)
  }
  parsed[[idx]]
}

first_matching_col <- function(df, candidates) {
  nm <- names(df)
  for (cand in candidates) {
    if (cand %in% nm) {
      return(as.character(df[[cand]][1]))
    }
  }
  # Regex fallbacks for Kleborate v3 prefixed headers.
  for (pat in candidates) {
    if (!grepl("__", pat)) {
      next
    }
  }
  for (cand in candidates) {
    hit <- grep(paste0("(^|_)", cand, "$"), nm, value = TRUE, ignore.case = TRUE)
    if (length(hit) == 1) {
      return(as.character(df[[hit]][1]))
    }
  }
  NA_character_
}

run_kleborate <- function(manifest_df, cfg, out_dir, tools) {
  emit_warn <- isTRUE(cfg$runtime$verbose)
  raw_dir <- file.path(out_dir, "kleborate_raw")
  fs::dir_create(raw_dir)
  out_rows <- purrr::map_dfr(seq_len(nrow(manifest_df)), function(i) {
    sid <- manifest_df$Sample_ID[i]
    fasta <- manifest_df$Input_FASTA[i]
    sample_dir <- file.path(raw_dir, sid)
    fs::dir_create(sample_dir)
    status <- "not_run"
    species <- NA_character_
    lineage <- NA_character_
    virulence_score <- NA_real_
    aerobactin <- NA_character_
    salmochelin <- NA_character_
    rmpA <- NA_character_
    rmpA2 <- NA_character_
    warn_reason <- NA_character_

    log_info(glue::glue("[Kleborate] ({i}/{nrow(manifest_df)}) {sid}"))

    klebo_bin <- get_tool(tools, "kleborate")
    if (!is.null(klebo_bin)) {
      res <- tryCatch(
        run_external_tool(
          klebo_bin,
          args = c("-a", fasta, "-o", sample_dir, "-p", "kpsc")
        ),
        error = function(e) NULL
      )
      if (!is.null(res) && isTRUE(res$status == 0)) {
        status <- "ok"
        readr::write_lines(res$stdout, file.path(sample_dir, "kleborate.stdout.log"))
        readr::write_lines(res$stderr, file.path(sample_dir, "kleborate.stderr.log"))
        txt <- list.files(sample_dir, pattern = "\\.txt$", full.names = TRUE)
        df <- pick_kleborate_table(txt)
        if (!is.null(df) && nrow(df) > 0) {
          species <- first_matching_col(df, c(
            "species", "Species", "enterobacterales__species__species"
          ))
          lineage <- first_matching_col(df, c(
            "st", "ST", "lineage", "klebsiella_pneumo_complex__mlst__ST"
          ))
          virulence_score <- suppressWarnings(as.numeric(first_matching_col(df, c(
            "virulence_score", "virulence_score/kleb",
            "klebsiella_pneumo_complex__virulence_score__virulence_score"
          ))))
          aerobactin <- first_matching_col(df, c(
            "iuc", "aerobactin", "Aerobactin", "klebsiella__abst__Aerobactin"
          ))
          salmochelin <- first_matching_col(df, c(
            "iro", "salmochelin", "Salmochelin", "klebsiella__smst__Salmochelin"
          ))
          rmpA <- first_matching_col(df, c("rmpA", "klebsiella__rmst__rmpA"))
          rmpA2 <- first_matching_col(df, c("rmpA2", "klebsiella__rmpa2__rmpA2"))
          if (all(is.na(c(species, lineage, virulence_score, aerobactin, salmochelin, rmpA, rmpA2)))) {
            warn_reason <- "No typing/virulence columns found in Kleborate output tables."
          }
        } else {
          # Kleborate may exit 0 while skipping non-Kp assemblies (stdout only).
          if (any(grepl("does not match any specified species|failed in check is_kp_complex",
                        res$stdout, ignore.case = TRUE))) {
            status <- "skipped"
            warn_reason <- "Assembly skipped by Kleborate (not Klebsiella pneumoniae complex)."
          } else {
            warn_reason <- "No readable .txt output generated by Kleborate."
          }
        }
      } else {
        status <- "failed"
        warn_reason <- "Kleborate command failed."
        if (!is.null(res)) {
          readr::write_lines(res$stdout, file.path(sample_dir, "kleborate.stdout.log"))
          readr::write_lines(res$stderr, file.path(sample_dir, "kleborate.stderr.log"))
        }
      }
    } else {
      warn_reason <- "kleborate executable not available."
    }

    if (emit_warn && !is.na(warn_reason)) {
      log_warn(glue::glue("[Kleborate] {sid}: {warn_reason}"))
    }
    tibble::tibble(
      Sample_ID = sid,
      Kleborate_Status = status,
      Species = species,
      ST_or_Lineage = lineage,
      Kleborate_Virulence_Score = virulence_score,
      Aerobactin = aerobactin,
      Salmochelin = salmochelin,
      rmpA = rmpA,
      rmpA2 = rmpA2
    )
  })
  readr::write_tsv(out_rows, file.path(out_dir, "kleborate_summary.tsv"))
  out_rows
}
